language: c
compiler: gcc
os: linux
dist: bionic
arch: arm64
services:
  - docker

env:
  global:
    - DOCKER=sfalexrog/raspbian:buster-2019-09-30
  jobs:
    - KVER=4.19.75+
    - KVER=4.19.75-v7+
    - KVER=4.19.75-v7l+

before_script:
  - mkdir -p ${HOME}/output
  - sudo docker pull ${DOCKER}

script:
  - sudo docker run --rm -v $(pwd):/realtek-rtl88xxau-dkms-5.2.20 -v ${HOME}/output:/output --env KVER=${KVER} ${DOCKER} /bin/bash -c '
      apt update && apt install -y bc build-essential debhelper dkms fakeroot &&
      cd realtek-rtl88xxau-dkms-5.2.20 && dpkg-buildpackage &&
      cp ci/rpi-control /etc/dkms/template-dkms-mkbmdeb/debian/control && cd / &&
      apt install ./*.deb &&
      dkms mkbmdeb realtek-rtl88xxau/5.2.20 -k ${KVER} &&
      cp /var/lib/dkms/realtek-rtl88xxau/5.2.20/bmdeb/*.deb /output'
  - find ${HOME}/output -iname '*.deb' -exec dpkg -I {} \;
